spring:
  application:
    name: Ribbon-Client
    
helloworld:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:8082,localhost:8083
    ServerListRefreshInterval: 1000
server:
  port: 9090