package com.sun.entity.autodao;

import com.sun.entity.automodel.Fs_kp01;
import com.sun.entity.automodel.Fs_kp01Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Fs_kp01Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp01
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    long countByExample(Fs_kp01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp01
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int deleteByExample(Fs_kp01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp01
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int insert(Fs_kp01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp01
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int insertSelective(Fs_kp01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp01
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    List<Fs_kp01> selectByExample(Fs_kp01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp01
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") Fs_kp01 record, @Param("example") Fs_kp01Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp01
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int updateByExample(@Param("record") Fs_kp01 record, @Param("example") Fs_kp01Example example);
}