package com.sun.entity.autodao;

import com.sun.entity.automodel.Fs_sfxm;
import com.sun.entity.automodel.Fs_sfxmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Fs_sfxmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_sfxm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    long countByExample(Fs_sfxmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_sfxm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int deleteByExample(Fs_sfxmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_sfxm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int insert(Fs_sfxm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_sfxm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int insertSelective(Fs_sfxm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_sfxm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    List<Fs_sfxm> selectByExample(Fs_sfxmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_sfxm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") Fs_sfxm record, @Param("example") Fs_sfxmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_sfxm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int updateByExample(@Param("record") Fs_sfxm record, @Param("example") Fs_sfxmExample example);
}