package com.sun.entity.autodao;

import com.sun.entity.automodel.Fs_yhwd;
import com.sun.entity.automodel.Fs_yhwdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Fs_yhwdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_yhwd
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    long countByExample(Fs_yhwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_yhwd
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int deleteByExample(Fs_yhwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_yhwd
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int insert(Fs_yhwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_yhwd
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int insertSelective(Fs_yhwd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_yhwd
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    List<Fs_yhwd> selectByExample(Fs_yhwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_yhwd
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") Fs_yhwd record, @Param("example") Fs_yhwdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_yhwd
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    int updateByExample(@Param("record") Fs_yhwd record, @Param("example") Fs_yhwdExample example);
}