package MapDbSample;

import java.io.Serializable;
import java.util.Date;

public class PriceIndex implements Serializable {
    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_D_PRICEINDEX.ID
     * <br>The field is the table primary key.
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    private long id;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_D_PRICEINDEX.CONTRACT
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    private String contract;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_D_PRICEINDEX.PRICE
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    private Long price;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_D_PRICEINDEX.UP_DOWN
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    private Long upDown;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_D_PRICEINDEX.TRADE_QTY
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    private Long tradeQty;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_D_PRICEINDEX.ORDER_QTY
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    private Long orderQty;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_D_PRICEINDEX.USER_ID
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    private Long userId;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_D_PRICEINDEX.CREATE_TIME
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    private Date createTime;

    /**
     * This field was generated by www.sacool.com iBATIS builder.
     * <br>This field corresponds to the database column T_D_PRICEINDEX.CONTRACT_ID
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    private String contractId;

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>Copy method of T_D_PRICEINDEX
     * @param priceIndex
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public void copy(PriceIndex priceIndex) {
        priceIndex.id = this.id;
        priceIndex.contract = this.contract;
        priceIndex.price = this.price;
        priceIndex.upDown = this.upDown;
        priceIndex.tradeQty = this.tradeQty;
        priceIndex.orderQty = this.orderQty;
        priceIndex.userId = this.userId;
        priceIndex.createTime = this.createTime;
        priceIndex.contractId = this.contractId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_D_PRICEINDEX.ID
     *
     * @return the value of T_D_PRICEINDEX.ID Primary Key
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public long getId() {
        return id;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_D_PRICEINDEX.ID
     *
     * @param id the value for T_D_PRICEINDEX.ID Primary Key
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_D_PRICEINDEX.CONTRACT
     *
     * @return the value of T_D_PRICEINDEX.CONTRACT
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_D_PRICEINDEX.CONTRACT
     *
     * @param contract the value for T_D_PRICEINDEX.CONTRACT
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public void setContract(String contract) {
        this.contract = contract;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_D_PRICEINDEX.PRICE
     *
     * @return the value of T_D_PRICEINDEX.PRICE
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_D_PRICEINDEX.PRICE
     *
     * @param price the value for T_D_PRICEINDEX.PRICE
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_D_PRICEINDEX.UP_DOWN
     *
     * @return the value of T_D_PRICEINDEX.UP_DOWN
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public Long getUpDown() {
        return upDown;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_D_PRICEINDEX.UP_DOWN
     *
     * @param upDown the value for T_D_PRICEINDEX.UP_DOWN
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public void setUpDown(Long upDown) {
        this.upDown = upDown;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_D_PRICEINDEX.TRADE_QTY
     *
     * @return the value of T_D_PRICEINDEX.TRADE_QTY
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public Long getTradeQty() {
        return tradeQty;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_D_PRICEINDEX.TRADE_QTY
     *
     * @param tradeQty the value for T_D_PRICEINDEX.TRADE_QTY
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public void setTradeQty(Long tradeQty) {
        this.tradeQty = tradeQty;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_D_PRICEINDEX.ORDER_QTY
     *
     * @return the value of T_D_PRICEINDEX.ORDER_QTY
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public Long getOrderQty() {
        return orderQty;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_D_PRICEINDEX.ORDER_QTY
     *
     * @param orderQty the value for T_D_PRICEINDEX.ORDER_QTY
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public void setOrderQty(Long orderQty) {
        this.orderQty = orderQty;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_D_PRICEINDEX.USER_ID
     *
     * @return the value of T_D_PRICEINDEX.USER_ID
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_D_PRICEINDEX.USER_ID
     *
     * @param userId the value for T_D_PRICEINDEX.USER_ID
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_D_PRICEINDEX.CREATE_TIME
     *
     * @return the value of T_D_PRICEINDEX.CREATE_TIME
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_D_PRICEINDEX.CREATE_TIME
     *
     * @param createTime the value for T_D_PRICEINDEX.CREATE_TIME
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method returns the value of the database column T_D_PRICEINDEX.CONTRACT_ID
     *
     * @return the value of T_D_PRICEINDEX.CONTRACT_ID
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>This method sets the value of the database column T_D_PRICEINDEX.CONTRACT_ID
     *
     * @param contractId the value for T_D_PRICEINDEX.CONTRACT_ID
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by www.sacool.com iBATIS builder.
     * <br>toString
     *
     * @sacoolbuildergenerated 2017-07-14 16:10:16
     * @author sacool ibatis builder Team
     */
    public String toString() {
        StringBuilder sb = new StringBuilder("{");
        sb.append("id:");
        sb.append(this.id);
        sb.append(", contract:");
        sb.append(this.contract);
        sb.append(", price:");
        sb.append(this.price);
        sb.append(", upDown:");
        sb.append(this.upDown);
        sb.append(", tradeQty:");
        sb.append(this.tradeQty);
        sb.append(", orderQty:");
        sb.append(this.orderQty);
        sb.append(", userId:");
        sb.append(this.userId);
        sb.append(", createTime:");
        sb.append(this.createTime);
        sb.append(", contractId:");
        sb.append(this.contractId);
        sb.append("}");
        return sb.toString();
    }
}