package com.afis.jx.entity.autodao;

import com.afis.jx.entity.automodel.Fs_dwzb;
import com.afis.jx.entity.automodel.Fs_dwzbExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Fs_dwzbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_dwzb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    long countByExample(Fs_dwzbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_dwzb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    int deleteByExample(Fs_dwzbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_dwzb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    int insert(Fs_dwzb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_dwzb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    int insertSelective(Fs_dwzb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_dwzb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    List<Fs_dwzb> selectByExample(Fs_dwzbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_dwzb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Fs_dwzb record, @Param("example") Fs_dwzbExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_dwzb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    int updateByExample(@Param("record") Fs_dwzb record, @Param("example") Fs_dwzbExample example);
}