package com.afis.jx.entity.autodao;

import com.afis.jx.entity.automodel.Fs_kp08;
import com.afis.jx.entity.automodel.Fs_kp08Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Fs_kp08Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp08
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    long countByExample(Fs_kp08Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp08
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    int deleteByExample(Fs_kp08Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp08
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    int insert(Fs_kp08 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp08
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    int insertSelective(Fs_kp08 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp08
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    List<Fs_kp08> selectByExample(Fs_kp08Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp08
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") Fs_kp08 record, @Param("example") Fs_kp08Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp08
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    int updateByExample(@Param("record") Fs_kp08 record, @Param("example") Fs_kp08Example example);
}