package com.afis.jx.entity.automodel;

public class Fs_dwzb {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.dwdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String dwdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.dwmc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String dwmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.addr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.fzr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String fzr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.ssxt
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String ssxt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.zgbm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String zgbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.dwxz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String dwxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.yzbm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String yzbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.pgy
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String pgy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.pgysfz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String pgysfz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.tel
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.bzrs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int bzrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.zzrs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int zzrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.ltxrs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int ltxrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.lsrs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int lsrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.dwjb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String dwjb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.kpfs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String kpfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.dwtp
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String dwtp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.cwzg
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String cwzg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.dyzth
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String dyzth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.khh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String khh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.srhzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String srhzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.zchzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String zchzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.zgzbh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String zgzbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.sfxkzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String sfxkzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_str1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_str2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_str3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_str4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_str5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_int1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defInt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_int2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defInt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_int3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defInt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_int4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defInt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_int5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defInt5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_num1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defNum1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_num2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defNum2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_dt1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defDt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_dwzb.def_dt2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defDt2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.dwdm
     *
     * @return the value of fs_dwzb.dwdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDwdm() {
        return dwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.dwdm
     *
     * @param dwdm the value for fs_dwzb.dwdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDwdm(String dwdm) {
        this.dwdm = dwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.dwmc
     *
     * @return the value of fs_dwzb.dwmc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDwmc() {
        return dwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.dwmc
     *
     * @param dwmc the value for fs_dwzb.dwmc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDwmc(String dwmc) {
        this.dwmc = dwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.addr
     *
     * @return the value of fs_dwzb.addr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.addr
     *
     * @param addr the value for fs_dwzb.addr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.fzr
     *
     * @return the value of fs_dwzb.fzr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getFzr() {
        return fzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.fzr
     *
     * @param fzr the value for fs_dwzb.fzr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setFzr(String fzr) {
        this.fzr = fzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.ssxt
     *
     * @return the value of fs_dwzb.ssxt
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getSsxt() {
        return ssxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.ssxt
     *
     * @param ssxt the value for fs_dwzb.ssxt
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setSsxt(String ssxt) {
        this.ssxt = ssxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.zgbm
     *
     * @return the value of fs_dwzb.zgbm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getZgbm() {
        return zgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.zgbm
     *
     * @param zgbm the value for fs_dwzb.zgbm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setZgbm(String zgbm) {
        this.zgbm = zgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.dwxz
     *
     * @return the value of fs_dwzb.dwxz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDwxz() {
        return dwxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.dwxz
     *
     * @param dwxz the value for fs_dwzb.dwxz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDwxz(String dwxz) {
        this.dwxz = dwxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.yzbm
     *
     * @return the value of fs_dwzb.yzbm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getYzbm() {
        return yzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.yzbm
     *
     * @param yzbm the value for fs_dwzb.yzbm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setYzbm(String yzbm) {
        this.yzbm = yzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.pgy
     *
     * @return the value of fs_dwzb.pgy
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getPgy() {
        return pgy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.pgy
     *
     * @param pgy the value for fs_dwzb.pgy
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setPgy(String pgy) {
        this.pgy = pgy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.pgysfz
     *
     * @return the value of fs_dwzb.pgysfz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getPgysfz() {
        return pgysfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.pgysfz
     *
     * @param pgysfz the value for fs_dwzb.pgysfz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setPgysfz(String pgysfz) {
        this.pgysfz = pgysfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.tel
     *
     * @return the value of fs_dwzb.tel
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.tel
     *
     * @param tel the value for fs_dwzb.tel
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.bzrs
     *
     * @return the value of fs_dwzb.bzrs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getBzrs() {
        return bzrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.bzrs
     *
     * @param bzrs the value for fs_dwzb.bzrs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setBzrs(int bzrs) {
        this.bzrs = bzrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.zzrs
     *
     * @return the value of fs_dwzb.zzrs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getZzrs() {
        return zzrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.zzrs
     *
     * @param zzrs the value for fs_dwzb.zzrs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setZzrs(int zzrs) {
        this.zzrs = zzrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.ltxrs
     *
     * @return the value of fs_dwzb.ltxrs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getLtxrs() {
        return ltxrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.ltxrs
     *
     * @param ltxrs the value for fs_dwzb.ltxrs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setLtxrs(int ltxrs) {
        this.ltxrs = ltxrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.lsrs
     *
     * @return the value of fs_dwzb.lsrs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getLsrs() {
        return lsrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.lsrs
     *
     * @param lsrs the value for fs_dwzb.lsrs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setLsrs(int lsrs) {
        this.lsrs = lsrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.dwjb
     *
     * @return the value of fs_dwzb.dwjb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDwjb() {
        return dwjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.dwjb
     *
     * @param dwjb the value for fs_dwzb.dwjb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDwjb(String dwjb) {
        this.dwjb = dwjb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.kpfs
     *
     * @return the value of fs_dwzb.kpfs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getKpfs() {
        return kpfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.kpfs
     *
     * @param kpfs the value for fs_dwzb.kpfs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setKpfs(String kpfs) {
        this.kpfs = kpfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.dwtp
     *
     * @return the value of fs_dwzb.dwtp
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDwtp() {
        return dwtp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.dwtp
     *
     * @param dwtp the value for fs_dwzb.dwtp
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDwtp(String dwtp) {
        this.dwtp = dwtp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.cwzg
     *
     * @return the value of fs_dwzb.cwzg
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getCwzg() {
        return cwzg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.cwzg
     *
     * @param cwzg the value for fs_dwzb.cwzg
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setCwzg(String cwzg) {
        this.cwzg = cwzg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.dyzth
     *
     * @return the value of fs_dwzb.dyzth
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDyzth() {
        return dyzth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.dyzth
     *
     * @param dyzth the value for fs_dwzb.dyzth
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDyzth(String dyzth) {
        this.dyzth = dyzth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.khh
     *
     * @return the value of fs_dwzb.khh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getKhh() {
        return khh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.khh
     *
     * @param khh the value for fs_dwzb.khh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setKhh(String khh) {
        this.khh = khh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.srhzh
     *
     * @return the value of fs_dwzb.srhzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getSrhzh() {
        return srhzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.srhzh
     *
     * @param srhzh the value for fs_dwzb.srhzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setSrhzh(String srhzh) {
        this.srhzh = srhzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.zchzh
     *
     * @return the value of fs_dwzb.zchzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getZchzh() {
        return zchzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.zchzh
     *
     * @param zchzh the value for fs_dwzb.zchzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setZchzh(String zchzh) {
        this.zchzh = zchzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.zgzbh
     *
     * @return the value of fs_dwzb.zgzbh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getZgzbh() {
        return zgzbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.zgzbh
     *
     * @param zgzbh the value for fs_dwzb.zgzbh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setZgzbh(String zgzbh) {
        this.zgzbh = zgzbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.sfxkzh
     *
     * @return the value of fs_dwzb.sfxkzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getSfxkzh() {
        return sfxkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.sfxkzh
     *
     * @param sfxkzh the value for fs_dwzb.sfxkzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setSfxkzh(String sfxkzh) {
        this.sfxkzh = sfxkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_str1
     *
     * @return the value of fs_dwzb.def_str1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr1() {
        return defStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_str1
     *
     * @param defStr1 the value for fs_dwzb.def_str1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr1(String defStr1) {
        this.defStr1 = defStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_str2
     *
     * @return the value of fs_dwzb.def_str2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr2() {
        return defStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_str2
     *
     * @param defStr2 the value for fs_dwzb.def_str2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr2(String defStr2) {
        this.defStr2 = defStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_str3
     *
     * @return the value of fs_dwzb.def_str3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr3() {
        return defStr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_str3
     *
     * @param defStr3 the value for fs_dwzb.def_str3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr3(String defStr3) {
        this.defStr3 = defStr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_str4
     *
     * @return the value of fs_dwzb.def_str4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr4() {
        return defStr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_str4
     *
     * @param defStr4 the value for fs_dwzb.def_str4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr4(String defStr4) {
        this.defStr4 = defStr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_str5
     *
     * @return the value of fs_dwzb.def_str5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr5() {
        return defStr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_str5
     *
     * @param defStr5 the value for fs_dwzb.def_str5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr5(String defStr5) {
        this.defStr5 = defStr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_int1
     *
     * @return the value of fs_dwzb.def_int1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefInt1() {
        return defInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_int1
     *
     * @param defInt1 the value for fs_dwzb.def_int1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt1(String defInt1) {
        this.defInt1 = defInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_int2
     *
     * @return the value of fs_dwzb.def_int2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefInt2() {
        return defInt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_int2
     *
     * @param defInt2 the value for fs_dwzb.def_int2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt2(String defInt2) {
        this.defInt2 = defInt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_int3
     *
     * @return the value of fs_dwzb.def_int3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefInt3() {
        return defInt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_int3
     *
     * @param defInt3 the value for fs_dwzb.def_int3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt3(String defInt3) {
        this.defInt3 = defInt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_int4
     *
     * @return the value of fs_dwzb.def_int4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefInt4() {
        return defInt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_int4
     *
     * @param defInt4 the value for fs_dwzb.def_int4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt4(String defInt4) {
        this.defInt4 = defInt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_int5
     *
     * @return the value of fs_dwzb.def_int5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefInt5() {
        return defInt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_int5
     *
     * @param defInt5 the value for fs_dwzb.def_int5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt5(String defInt5) {
        this.defInt5 = defInt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_num1
     *
     * @return the value of fs_dwzb.def_num1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefNum1() {
        return defNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_num1
     *
     * @param defNum1 the value for fs_dwzb.def_num1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefNum1(String defNum1) {
        this.defNum1 = defNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_num2
     *
     * @return the value of fs_dwzb.def_num2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefNum2() {
        return defNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_num2
     *
     * @param defNum2 the value for fs_dwzb.def_num2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefNum2(String defNum2) {
        this.defNum2 = defNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_dt1
     *
     * @return the value of fs_dwzb.def_dt1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefDt1() {
        return defDt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_dt1
     *
     * @param defDt1 the value for fs_dwzb.def_dt1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefDt1(String defDt1) {
        this.defDt1 = defDt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_dwzb.def_dt2
     *
     * @return the value of fs_dwzb.def_dt2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefDt2() {
        return defDt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_dwzb.def_dt2
     *
     * @param defDt2 the value for fs_dwzb.def_dt2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefDt2(String defDt2) {
        this.defDt2 = defDt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_dwzb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dwdm=").append(dwdm);
        sb.append(", dwmc=").append(dwmc);
        sb.append(", addr=").append(addr);
        sb.append(", fzr=").append(fzr);
        sb.append(", ssxt=").append(ssxt);
        sb.append(", zgbm=").append(zgbm);
        sb.append(", dwxz=").append(dwxz);
        sb.append(", yzbm=").append(yzbm);
        sb.append(", pgy=").append(pgy);
        sb.append(", pgysfz=").append(pgysfz);
        sb.append(", tel=").append(tel);
        sb.append(", bzrs=").append(bzrs);
        sb.append(", zzrs=").append(zzrs);
        sb.append(", ltxrs=").append(ltxrs);
        sb.append(", lsrs=").append(lsrs);
        sb.append(", dwjb=").append(dwjb);
        sb.append(", kpfs=").append(kpfs);
        sb.append(", dwtp=").append(dwtp);
        sb.append(", cwzg=").append(cwzg);
        sb.append(", dyzth=").append(dyzth);
        sb.append(", khh=").append(khh);
        sb.append(", srhzh=").append(srhzh);
        sb.append(", zchzh=").append(zchzh);
        sb.append(", zgzbh=").append(zgzbh);
        sb.append(", sfxkzh=").append(sfxkzh);
        sb.append(", defStr1=").append(defStr1);
        sb.append(", defStr2=").append(defStr2);
        sb.append(", defStr3=").append(defStr3);
        sb.append(", defStr4=").append(defStr4);
        sb.append(", defStr5=").append(defStr5);
        sb.append(", defInt1=").append(defInt1);
        sb.append(", defInt2=").append(defInt2);
        sb.append(", defInt3=").append(defInt3);
        sb.append(", defInt4=").append(defInt4);
        sb.append(", defInt5=").append(defInt5);
        sb.append(", defNum1=").append(defNum1);
        sb.append(", defNum2=").append(defNum2);
        sb.append(", defDt1=").append(defDt1);
        sb.append(", defDt2=").append(defDt2);
        sb.append("]");
        return sb.toString();
    }
}