package com.afis.jx.entity.automodel;

public class Fs_jsfs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_jsfs.dm
     *
     * @mbg.generated Thu Jul 05 10:53:48 CST 2018
     */
    private int dm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_jsfs.mc
     *
     * @mbg.generated Thu Jul 05 10:53:48 CST 2018
     */
    private String mc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_jsfs.dm
     *
     * @return the value of fs_jsfs.dm
     *
     * @mbg.generated Thu Jul 05 10:53:48 CST 2018
     */
    public int getDm() {
        return dm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_jsfs.dm
     *
     * @param dm the value for fs_jsfs.dm
     *
     * @mbg.generated Thu Jul 05 10:53:48 CST 2018
     */
    public void setDm(int dm) {
        this.dm = dm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_jsfs.mc
     *
     * @return the value of fs_jsfs.mc
     *
     * @mbg.generated Thu Jul 05 10:53:48 CST 2018
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_jsfs.mc
     *
     * @param mc the value for fs_jsfs.mc
     *
     * @mbg.generated Thu Jul 05 10:53:48 CST 2018
     */
    public void setMc(String mc) {
        this.mc = mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_jsfs
     *
     * @mbg.generated Thu Jul 05 10:53:48 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dm=").append(dm);
        sb.append(", mc=").append(mc);
        sb.append("]");
        return sb.toString();
    }
}