package com.afis.jx.entity.automodel;

public class Fs_kp05 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.id1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String id1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.id2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int id2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.dwdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String dwdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.yhdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String yhdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.wddm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String wddm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.pjrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String pjrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.pjlx
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String pjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.zgbm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String zgbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.pjh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String pjh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.jksh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String jksh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.jkrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String jkrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.jkr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String jkr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.xmdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String xmdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.zy
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String zy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.je
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String je;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.dw
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String dw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.sl
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String sl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.sfbz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String sfbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.kpr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String kpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.jsr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String jsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.shr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String shr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.hxr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String hxr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.jsfs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int jsfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.jspjh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String jspjh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.jsyh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String jsyh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.wldwdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String wldwdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.wldwmc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String wldwmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.wldwkh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String wldwkh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.wldwzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String wldwzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.pjzt
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String pjzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.tg_pzlx
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String tgPzlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.tg_pzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String tgPzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.tg_pzrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String tgPzrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.st_pzlx
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String stPzlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.st_pzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String stPzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.st_pzrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String stPzrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.bz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.iszh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String iszh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.isprint
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String isprint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.isdwkp
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String isdwkp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.isyhkp
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String isyhkp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.isdwjk
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String isdwjk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_str1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_str2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_str3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_str4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_str5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_int1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int defInt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_int2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int defInt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_int3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int defInt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_int4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int defInt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_int5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int defInt5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_num1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defNum1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_num2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defNum2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_num3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defNum3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_num4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defNum4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_num5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defNum5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_dt1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defDt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.def_dt2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defDt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.ishz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String ishz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.cpdw
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String cpdw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.fyhdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String fyhdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.fyhzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String fyhzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_kp05.istf
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String istf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.id1
     *
     * @return the value of fs_kp05.id1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getId1() {
        return id1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.id1
     *
     * @param id1 the value for fs_kp05.id1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setId1(String id1) {
        this.id1 = id1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.id2
     *
     * @return the value of fs_kp05.id2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getId2() {
        return id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.id2
     *
     * @param id2 the value for fs_kp05.id2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setId2(int id2) {
        this.id2 = id2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.dwdm
     *
     * @return the value of fs_kp05.dwdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDwdm() {
        return dwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.dwdm
     *
     * @param dwdm the value for fs_kp05.dwdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDwdm(String dwdm) {
        this.dwdm = dwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.yhdm
     *
     * @return the value of fs_kp05.yhdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getYhdm() {
        return yhdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.yhdm
     *
     * @param yhdm the value for fs_kp05.yhdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setYhdm(String yhdm) {
        this.yhdm = yhdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.wddm
     *
     * @return the value of fs_kp05.wddm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getWddm() {
        return wddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.wddm
     *
     * @param wddm the value for fs_kp05.wddm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setWddm(String wddm) {
        this.wddm = wddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.pjrq
     *
     * @return the value of fs_kp05.pjrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getPjrq() {
        return pjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.pjrq
     *
     * @param pjrq the value for fs_kp05.pjrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setPjrq(String pjrq) {
        this.pjrq = pjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.pjlx
     *
     * @return the value of fs_kp05.pjlx
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getPjlx() {
        return pjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.pjlx
     *
     * @param pjlx the value for fs_kp05.pjlx
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setPjlx(String pjlx) {
        this.pjlx = pjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.zgbm
     *
     * @return the value of fs_kp05.zgbm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getZgbm() {
        return zgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.zgbm
     *
     * @param zgbm the value for fs_kp05.zgbm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setZgbm(String zgbm) {
        this.zgbm = zgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.pjh
     *
     * @return the value of fs_kp05.pjh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getPjh() {
        return pjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.pjh
     *
     * @param pjh the value for fs_kp05.pjh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setPjh(String pjh) {
        this.pjh = pjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.jksh
     *
     * @return the value of fs_kp05.jksh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getJksh() {
        return jksh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.jksh
     *
     * @param jksh the value for fs_kp05.jksh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setJksh(String jksh) {
        this.jksh = jksh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.jkrq
     *
     * @return the value of fs_kp05.jkrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getJkrq() {
        return jkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.jkrq
     *
     * @param jkrq the value for fs_kp05.jkrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setJkrq(String jkrq) {
        this.jkrq = jkrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.jkr
     *
     * @return the value of fs_kp05.jkr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getJkr() {
        return jkr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.jkr
     *
     * @param jkr the value for fs_kp05.jkr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setJkr(String jkr) {
        this.jkr = jkr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.xmdm
     *
     * @return the value of fs_kp05.xmdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getXmdm() {
        return xmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.xmdm
     *
     * @param xmdm the value for fs_kp05.xmdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setXmdm(String xmdm) {
        this.xmdm = xmdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.zy
     *
     * @return the value of fs_kp05.zy
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.zy
     *
     * @param zy the value for fs_kp05.zy
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setZy(String zy) {
        this.zy = zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.je
     *
     * @return the value of fs_kp05.je
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getJe() {
        return je;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.je
     *
     * @param je the value for fs_kp05.je
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setJe(String je) {
        this.je = je;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.dw
     *
     * @return the value of fs_kp05.dw
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDw() {
        return dw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.dw
     *
     * @param dw the value for fs_kp05.dw
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDw(String dw) {
        this.dw = dw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.sl
     *
     * @return the value of fs_kp05.sl
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getSl() {
        return sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.sl
     *
     * @param sl the value for fs_kp05.sl
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setSl(String sl) {
        this.sl = sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.sfbz
     *
     * @return the value of fs_kp05.sfbz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getSfbz() {
        return sfbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.sfbz
     *
     * @param sfbz the value for fs_kp05.sfbz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setSfbz(String sfbz) {
        this.sfbz = sfbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.kpr
     *
     * @return the value of fs_kp05.kpr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getKpr() {
        return kpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.kpr
     *
     * @param kpr the value for fs_kp05.kpr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setKpr(String kpr) {
        this.kpr = kpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.jsr
     *
     * @return the value of fs_kp05.jsr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getJsr() {
        return jsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.jsr
     *
     * @param jsr the value for fs_kp05.jsr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setJsr(String jsr) {
        this.jsr = jsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.shr
     *
     * @return the value of fs_kp05.shr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getShr() {
        return shr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.shr
     *
     * @param shr the value for fs_kp05.shr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setShr(String shr) {
        this.shr = shr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.hxr
     *
     * @return the value of fs_kp05.hxr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getHxr() {
        return hxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.hxr
     *
     * @param hxr the value for fs_kp05.hxr
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setHxr(String hxr) {
        this.hxr = hxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.jsfs
     *
     * @return the value of fs_kp05.jsfs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getJsfs() {
        return jsfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.jsfs
     *
     * @param jsfs the value for fs_kp05.jsfs
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setJsfs(int jsfs) {
        this.jsfs = jsfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.jspjh
     *
     * @return the value of fs_kp05.jspjh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getJspjh() {
        return jspjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.jspjh
     *
     * @param jspjh the value for fs_kp05.jspjh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setJspjh(String jspjh) {
        this.jspjh = jspjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.jsyh
     *
     * @return the value of fs_kp05.jsyh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getJsyh() {
        return jsyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.jsyh
     *
     * @param jsyh the value for fs_kp05.jsyh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setJsyh(String jsyh) {
        this.jsyh = jsyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.wldwdm
     *
     * @return the value of fs_kp05.wldwdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getWldwdm() {
        return wldwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.wldwdm
     *
     * @param wldwdm the value for fs_kp05.wldwdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setWldwdm(String wldwdm) {
        this.wldwdm = wldwdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.wldwmc
     *
     * @return the value of fs_kp05.wldwmc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getWldwmc() {
        return wldwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.wldwmc
     *
     * @param wldwmc the value for fs_kp05.wldwmc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setWldwmc(String wldwmc) {
        this.wldwmc = wldwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.wldwkh
     *
     * @return the value of fs_kp05.wldwkh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getWldwkh() {
        return wldwkh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.wldwkh
     *
     * @param wldwkh the value for fs_kp05.wldwkh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setWldwkh(String wldwkh) {
        this.wldwkh = wldwkh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.wldwzh
     *
     * @return the value of fs_kp05.wldwzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getWldwzh() {
        return wldwzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.wldwzh
     *
     * @param wldwzh the value for fs_kp05.wldwzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setWldwzh(String wldwzh) {
        this.wldwzh = wldwzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.pjzt
     *
     * @return the value of fs_kp05.pjzt
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getPjzt() {
        return pjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.pjzt
     *
     * @param pjzt the value for fs_kp05.pjzt
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setPjzt(String pjzt) {
        this.pjzt = pjzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.tg_pzlx
     *
     * @return the value of fs_kp05.tg_pzlx
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getTgPzlx() {
        return tgPzlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.tg_pzlx
     *
     * @param tgPzlx the value for fs_kp05.tg_pzlx
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setTgPzlx(String tgPzlx) {
        this.tgPzlx = tgPzlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.tg_pzh
     *
     * @return the value of fs_kp05.tg_pzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getTgPzh() {
        return tgPzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.tg_pzh
     *
     * @param tgPzh the value for fs_kp05.tg_pzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setTgPzh(String tgPzh) {
        this.tgPzh = tgPzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.tg_pzrq
     *
     * @return the value of fs_kp05.tg_pzrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getTgPzrq() {
        return tgPzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.tg_pzrq
     *
     * @param tgPzrq the value for fs_kp05.tg_pzrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setTgPzrq(String tgPzrq) {
        this.tgPzrq = tgPzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.st_pzlx
     *
     * @return the value of fs_kp05.st_pzlx
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getStPzlx() {
        return stPzlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.st_pzlx
     *
     * @param stPzlx the value for fs_kp05.st_pzlx
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setStPzlx(String stPzlx) {
        this.stPzlx = stPzlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.st_pzh
     *
     * @return the value of fs_kp05.st_pzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getStPzh() {
        return stPzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.st_pzh
     *
     * @param stPzh the value for fs_kp05.st_pzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setStPzh(String stPzh) {
        this.stPzh = stPzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.st_pzrq
     *
     * @return the value of fs_kp05.st_pzrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getStPzrq() {
        return stPzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.st_pzrq
     *
     * @param stPzrq the value for fs_kp05.st_pzrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setStPzrq(String stPzrq) {
        this.stPzrq = stPzrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.bz
     *
     * @return the value of fs_kp05.bz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.bz
     *
     * @param bz the value for fs_kp05.bz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setBz(String bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.iszh
     *
     * @return the value of fs_kp05.iszh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getIszh() {
        return iszh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.iszh
     *
     * @param iszh the value for fs_kp05.iszh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setIszh(String iszh) {
        this.iszh = iszh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.isprint
     *
     * @return the value of fs_kp05.isprint
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getIsprint() {
        return isprint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.isprint
     *
     * @param isprint the value for fs_kp05.isprint
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setIsprint(String isprint) {
        this.isprint = isprint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.isdwkp
     *
     * @return the value of fs_kp05.isdwkp
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getIsdwkp() {
        return isdwkp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.isdwkp
     *
     * @param isdwkp the value for fs_kp05.isdwkp
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setIsdwkp(String isdwkp) {
        this.isdwkp = isdwkp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.isyhkp
     *
     * @return the value of fs_kp05.isyhkp
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getIsyhkp() {
        return isyhkp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.isyhkp
     *
     * @param isyhkp the value for fs_kp05.isyhkp
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setIsyhkp(String isyhkp) {
        this.isyhkp = isyhkp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.isdwjk
     *
     * @return the value of fs_kp05.isdwjk
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getIsdwjk() {
        return isdwjk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.isdwjk
     *
     * @param isdwjk the value for fs_kp05.isdwjk
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setIsdwjk(String isdwjk) {
        this.isdwjk = isdwjk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_str1
     *
     * @return the value of fs_kp05.def_str1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr1() {
        return defStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_str1
     *
     * @param defStr1 the value for fs_kp05.def_str1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr1(String defStr1) {
        this.defStr1 = defStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_str2
     *
     * @return the value of fs_kp05.def_str2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr2() {
        return defStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_str2
     *
     * @param defStr2 the value for fs_kp05.def_str2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr2(String defStr2) {
        this.defStr2 = defStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_str3
     *
     * @return the value of fs_kp05.def_str3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr3() {
        return defStr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_str3
     *
     * @param defStr3 the value for fs_kp05.def_str3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr3(String defStr3) {
        this.defStr3 = defStr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_str4
     *
     * @return the value of fs_kp05.def_str4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr4() {
        return defStr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_str4
     *
     * @param defStr4 the value for fs_kp05.def_str4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr4(String defStr4) {
        this.defStr4 = defStr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_str5
     *
     * @return the value of fs_kp05.def_str5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr5() {
        return defStr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_str5
     *
     * @param defStr5 the value for fs_kp05.def_str5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr5(String defStr5) {
        this.defStr5 = defStr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_int1
     *
     * @return the value of fs_kp05.def_int1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getDefInt1() {
        return defInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_int1
     *
     * @param defInt1 the value for fs_kp05.def_int1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt1(int defInt1) {
        this.defInt1 = defInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_int2
     *
     * @return the value of fs_kp05.def_int2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getDefInt2() {
        return defInt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_int2
     *
     * @param defInt2 the value for fs_kp05.def_int2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt2(int defInt2) {
        this.defInt2 = defInt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_int3
     *
     * @return the value of fs_kp05.def_int3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getDefInt3() {
        return defInt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_int3
     *
     * @param defInt3 the value for fs_kp05.def_int3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt3(int defInt3) {
        this.defInt3 = defInt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_int4
     *
     * @return the value of fs_kp05.def_int4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getDefInt4() {
        return defInt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_int4
     *
     * @param defInt4 the value for fs_kp05.def_int4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt4(int defInt4) {
        this.defInt4 = defInt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_int5
     *
     * @return the value of fs_kp05.def_int5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getDefInt5() {
        return defInt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_int5
     *
     * @param defInt5 the value for fs_kp05.def_int5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt5(int defInt5) {
        this.defInt5 = defInt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_num1
     *
     * @return the value of fs_kp05.def_num1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefNum1() {
        return defNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_num1
     *
     * @param defNum1 the value for fs_kp05.def_num1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefNum1(String defNum1) {
        this.defNum1 = defNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_num2
     *
     * @return the value of fs_kp05.def_num2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefNum2() {
        return defNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_num2
     *
     * @param defNum2 the value for fs_kp05.def_num2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefNum2(String defNum2) {
        this.defNum2 = defNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_num3
     *
     * @return the value of fs_kp05.def_num3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefNum3() {
        return defNum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_num3
     *
     * @param defNum3 the value for fs_kp05.def_num3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefNum3(String defNum3) {
        this.defNum3 = defNum3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_num4
     *
     * @return the value of fs_kp05.def_num4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefNum4() {
        return defNum4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_num4
     *
     * @param defNum4 the value for fs_kp05.def_num4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefNum4(String defNum4) {
        this.defNum4 = defNum4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_num5
     *
     * @return the value of fs_kp05.def_num5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefNum5() {
        return defNum5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_num5
     *
     * @param defNum5 the value for fs_kp05.def_num5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefNum5(String defNum5) {
        this.defNum5 = defNum5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_dt1
     *
     * @return the value of fs_kp05.def_dt1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefDt1() {
        return defDt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_dt1
     *
     * @param defDt1 the value for fs_kp05.def_dt1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefDt1(String defDt1) {
        this.defDt1 = defDt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.def_dt2
     *
     * @return the value of fs_kp05.def_dt2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefDt2() {
        return defDt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.def_dt2
     *
     * @param defDt2 the value for fs_kp05.def_dt2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefDt2(String defDt2) {
        this.defDt2 = defDt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.ishz
     *
     * @return the value of fs_kp05.ishz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getIshz() {
        return ishz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.ishz
     *
     * @param ishz the value for fs_kp05.ishz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setIshz(String ishz) {
        this.ishz = ishz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.cpdw
     *
     * @return the value of fs_kp05.cpdw
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getCpdw() {
        return cpdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.cpdw
     *
     * @param cpdw the value for fs_kp05.cpdw
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setCpdw(String cpdw) {
        this.cpdw = cpdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.fyhdm
     *
     * @return the value of fs_kp05.fyhdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getFyhdm() {
        return fyhdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.fyhdm
     *
     * @param fyhdm the value for fs_kp05.fyhdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setFyhdm(String fyhdm) {
        this.fyhdm = fyhdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.fyhzh
     *
     * @return the value of fs_kp05.fyhzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getFyhzh() {
        return fyhzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.fyhzh
     *
     * @param fyhzh the value for fs_kp05.fyhzh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setFyhzh(String fyhzh) {
        this.fyhzh = fyhzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_kp05.istf
     *
     * @return the value of fs_kp05.istf
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getIstf() {
        return istf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_kp05.istf
     *
     * @param istf the value for fs_kp05.istf
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setIstf(String istf) {
        this.istf = istf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_kp05
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id1=").append(id1);
        sb.append(", id2=").append(id2);
        sb.append(", dwdm=").append(dwdm);
        sb.append(", yhdm=").append(yhdm);
        sb.append(", wddm=").append(wddm);
        sb.append(", pjrq=").append(pjrq);
        sb.append(", pjlx=").append(pjlx);
        sb.append(", zgbm=").append(zgbm);
        sb.append(", pjh=").append(pjh);
        sb.append(", jksh=").append(jksh);
        sb.append(", jkrq=").append(jkrq);
        sb.append(", jkr=").append(jkr);
        sb.append(", xmdm=").append(xmdm);
        sb.append(", zy=").append(zy);
        sb.append(", je=").append(je);
        sb.append(", dw=").append(dw);
        sb.append(", sl=").append(sl);
        sb.append(", sfbz=").append(sfbz);
        sb.append(", kpr=").append(kpr);
        sb.append(", jsr=").append(jsr);
        sb.append(", shr=").append(shr);
        sb.append(", hxr=").append(hxr);
        sb.append(", jsfs=").append(jsfs);
        sb.append(", jspjh=").append(jspjh);
        sb.append(", jsyh=").append(jsyh);
        sb.append(", wldwdm=").append(wldwdm);
        sb.append(", wldwmc=").append(wldwmc);
        sb.append(", wldwkh=").append(wldwkh);
        sb.append(", wldwzh=").append(wldwzh);
        sb.append(", pjzt=").append(pjzt);
        sb.append(", tgPzlx=").append(tgPzlx);
        sb.append(", tgPzh=").append(tgPzh);
        sb.append(", tgPzrq=").append(tgPzrq);
        sb.append(", stPzlx=").append(stPzlx);
        sb.append(", stPzh=").append(stPzh);
        sb.append(", stPzrq=").append(stPzrq);
        sb.append(", bz=").append(bz);
        sb.append(", iszh=").append(iszh);
        sb.append(", isprint=").append(isprint);
        sb.append(", isdwkp=").append(isdwkp);
        sb.append(", isyhkp=").append(isyhkp);
        sb.append(", isdwjk=").append(isdwjk);
        sb.append(", defStr1=").append(defStr1);
        sb.append(", defStr2=").append(defStr2);
        sb.append(", defStr3=").append(defStr3);
        sb.append(", defStr4=").append(defStr4);
        sb.append(", defStr5=").append(defStr5);
        sb.append(", defInt1=").append(defInt1);
        sb.append(", defInt2=").append(defInt2);
        sb.append(", defInt3=").append(defInt3);
        sb.append(", defInt4=").append(defInt4);
        sb.append(", defInt5=").append(defInt5);
        sb.append(", defNum1=").append(defNum1);
        sb.append(", defNum2=").append(defNum2);
        sb.append(", defNum3=").append(defNum3);
        sb.append(", defNum4=").append(defNum4);
        sb.append(", defNum5=").append(defNum5);
        sb.append(", defDt1=").append(defDt1);
        sb.append(", defDt2=").append(defDt2);
        sb.append(", ishz=").append(ishz);
        sb.append(", cpdw=").append(cpdw);
        sb.append(", fyhdm=").append(fyhdm);
        sb.append(", fyhzh=").append(fyhzh);
        sb.append(", istf=").append(istf);
        sb.append("]");
        return sb.toString();
    }
}