package com.afis.jx.entity.automodel;

public class Fs_sfxm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.dm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int dm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.mc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String mc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.sfdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String sfdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.sfyj
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String sfyj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.istc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String istc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.tlbl
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String tlbl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.zjxz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String zjxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.xmlb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String xmlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.isys
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String isys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.xmsp
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String xmsp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.srjc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String srjc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.sfbz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String sfbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.pzjg
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String pzjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.pzwh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String pzwh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.isqx
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String isqx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.qxrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String qxrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.qxwh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String qxwh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.bz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_str1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_str2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_str3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_str4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_str5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defStr5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_int1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int defInt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_int2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int defInt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_int3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int defInt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_int4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int defInt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_int5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private int defInt5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_num1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defNum1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_num2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defNum2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_dt1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defDt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_sfxm.def_dt2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    private String defDt2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.dm
     *
     * @return the value of fs_sfxm.dm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getDm() {
        return dm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.dm
     *
     * @param dm the value for fs_sfxm.dm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDm(int dm) {
        this.dm = dm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.mc
     *
     * @return the value of fs_sfxm.mc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.mc
     *
     * @param mc the value for fs_sfxm.mc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setMc(String mc) {
        this.mc = mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.sfdm
     *
     * @return the value of fs_sfxm.sfdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getSfdm() {
        return sfdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.sfdm
     *
     * @param sfdm the value for fs_sfxm.sfdm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setSfdm(String sfdm) {
        this.sfdm = sfdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.sfyj
     *
     * @return the value of fs_sfxm.sfyj
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getSfyj() {
        return sfyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.sfyj
     *
     * @param sfyj the value for fs_sfxm.sfyj
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setSfyj(String sfyj) {
        this.sfyj = sfyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.istc
     *
     * @return the value of fs_sfxm.istc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getIstc() {
        return istc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.istc
     *
     * @param istc the value for fs_sfxm.istc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setIstc(String istc) {
        this.istc = istc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.tlbl
     *
     * @return the value of fs_sfxm.tlbl
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getTlbl() {
        return tlbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.tlbl
     *
     * @param tlbl the value for fs_sfxm.tlbl
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setTlbl(String tlbl) {
        this.tlbl = tlbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.zjxz
     *
     * @return the value of fs_sfxm.zjxz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getZjxz() {
        return zjxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.zjxz
     *
     * @param zjxz the value for fs_sfxm.zjxz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setZjxz(String zjxz) {
        this.zjxz = zjxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.xmlb
     *
     * @return the value of fs_sfxm.xmlb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getXmlb() {
        return xmlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.xmlb
     *
     * @param xmlb the value for fs_sfxm.xmlb
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setXmlb(String xmlb) {
        this.xmlb = xmlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.isys
     *
     * @return the value of fs_sfxm.isys
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getIsys() {
        return isys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.isys
     *
     * @param isys the value for fs_sfxm.isys
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setIsys(String isys) {
        this.isys = isys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.xmsp
     *
     * @return the value of fs_sfxm.xmsp
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getXmsp() {
        return xmsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.xmsp
     *
     * @param xmsp the value for fs_sfxm.xmsp
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setXmsp(String xmsp) {
        this.xmsp = xmsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.srjc
     *
     * @return the value of fs_sfxm.srjc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getSrjc() {
        return srjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.srjc
     *
     * @param srjc the value for fs_sfxm.srjc
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setSrjc(String srjc) {
        this.srjc = srjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.sfbz
     *
     * @return the value of fs_sfxm.sfbz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getSfbz() {
        return sfbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.sfbz
     *
     * @param sfbz the value for fs_sfxm.sfbz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setSfbz(String sfbz) {
        this.sfbz = sfbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.pzjg
     *
     * @return the value of fs_sfxm.pzjg
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getPzjg() {
        return pzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.pzjg
     *
     * @param pzjg the value for fs_sfxm.pzjg
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setPzjg(String pzjg) {
        this.pzjg = pzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.pzwh
     *
     * @return the value of fs_sfxm.pzwh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getPzwh() {
        return pzwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.pzwh
     *
     * @param pzwh the value for fs_sfxm.pzwh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setPzwh(String pzwh) {
        this.pzwh = pzwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.isqx
     *
     * @return the value of fs_sfxm.isqx
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getIsqx() {
        return isqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.isqx
     *
     * @param isqx the value for fs_sfxm.isqx
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setIsqx(String isqx) {
        this.isqx = isqx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.qxrq
     *
     * @return the value of fs_sfxm.qxrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getQxrq() {
        return qxrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.qxrq
     *
     * @param qxrq the value for fs_sfxm.qxrq
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setQxrq(String qxrq) {
        this.qxrq = qxrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.qxwh
     *
     * @return the value of fs_sfxm.qxwh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getQxwh() {
        return qxwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.qxwh
     *
     * @param qxwh the value for fs_sfxm.qxwh
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setQxwh(String qxwh) {
        this.qxwh = qxwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.bz
     *
     * @return the value of fs_sfxm.bz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.bz
     *
     * @param bz the value for fs_sfxm.bz
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setBz(String bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_str1
     *
     * @return the value of fs_sfxm.def_str1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr1() {
        return defStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_str1
     *
     * @param defStr1 the value for fs_sfxm.def_str1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr1(String defStr1) {
        this.defStr1 = defStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_str2
     *
     * @return the value of fs_sfxm.def_str2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr2() {
        return defStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_str2
     *
     * @param defStr2 the value for fs_sfxm.def_str2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr2(String defStr2) {
        this.defStr2 = defStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_str3
     *
     * @return the value of fs_sfxm.def_str3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr3() {
        return defStr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_str3
     *
     * @param defStr3 the value for fs_sfxm.def_str3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr3(String defStr3) {
        this.defStr3 = defStr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_str4
     *
     * @return the value of fs_sfxm.def_str4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr4() {
        return defStr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_str4
     *
     * @param defStr4 the value for fs_sfxm.def_str4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr4(String defStr4) {
        this.defStr4 = defStr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_str5
     *
     * @return the value of fs_sfxm.def_str5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefStr5() {
        return defStr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_str5
     *
     * @param defStr5 the value for fs_sfxm.def_str5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefStr5(String defStr5) {
        this.defStr5 = defStr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_int1
     *
     * @return the value of fs_sfxm.def_int1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getDefInt1() {
        return defInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_int1
     *
     * @param defInt1 the value for fs_sfxm.def_int1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt1(int defInt1) {
        this.defInt1 = defInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_int2
     *
     * @return the value of fs_sfxm.def_int2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getDefInt2() {
        return defInt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_int2
     *
     * @param defInt2 the value for fs_sfxm.def_int2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt2(int defInt2) {
        this.defInt2 = defInt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_int3
     *
     * @return the value of fs_sfxm.def_int3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getDefInt3() {
        return defInt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_int3
     *
     * @param defInt3 the value for fs_sfxm.def_int3
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt3(int defInt3) {
        this.defInt3 = defInt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_int4
     *
     * @return the value of fs_sfxm.def_int4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getDefInt4() {
        return defInt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_int4
     *
     * @param defInt4 the value for fs_sfxm.def_int4
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt4(int defInt4) {
        this.defInt4 = defInt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_int5
     *
     * @return the value of fs_sfxm.def_int5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public int getDefInt5() {
        return defInt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_int5
     *
     * @param defInt5 the value for fs_sfxm.def_int5
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefInt5(int defInt5) {
        this.defInt5 = defInt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_num1
     *
     * @return the value of fs_sfxm.def_num1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefNum1() {
        return defNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_num1
     *
     * @param defNum1 the value for fs_sfxm.def_num1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefNum1(String defNum1) {
        this.defNum1 = defNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_num2
     *
     * @return the value of fs_sfxm.def_num2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefNum2() {
        return defNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_num2
     *
     * @param defNum2 the value for fs_sfxm.def_num2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefNum2(String defNum2) {
        this.defNum2 = defNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_dt1
     *
     * @return the value of fs_sfxm.def_dt1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefDt1() {
        return defDt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_dt1
     *
     * @param defDt1 the value for fs_sfxm.def_dt1
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefDt1(String defDt1) {
        this.defDt1 = defDt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_sfxm.def_dt2
     *
     * @return the value of fs_sfxm.def_dt2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public String getDefDt2() {
        return defDt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_sfxm.def_dt2
     *
     * @param defDt2 the value for fs_sfxm.def_dt2
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    public void setDefDt2(String defDt2) {
        this.defDt2 = defDt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_sfxm
     *
     * @mbg.generated Thu Jul 05 12:21:56 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dm=").append(dm);
        sb.append(", mc=").append(mc);
        sb.append(", sfdm=").append(sfdm);
        sb.append(", sfyj=").append(sfyj);
        sb.append(", istc=").append(istc);
        sb.append(", tlbl=").append(tlbl);
        sb.append(", zjxz=").append(zjxz);
        sb.append(", xmlb=").append(xmlb);
        sb.append(", isys=").append(isys);
        sb.append(", xmsp=").append(xmsp);
        sb.append(", srjc=").append(srjc);
        sb.append(", sfbz=").append(sfbz);
        sb.append(", pzjg=").append(pzjg);
        sb.append(", pzwh=").append(pzwh);
        sb.append(", isqx=").append(isqx);
        sb.append(", qxrq=").append(qxrq);
        sb.append(", qxwh=").append(qxwh);
        sb.append(", bz=").append(bz);
        sb.append(", defStr1=").append(defStr1);
        sb.append(", defStr2=").append(defStr2);
        sb.append(", defStr3=").append(defStr3);
        sb.append(", defStr4=").append(defStr4);
        sb.append(", defStr5=").append(defStr5);
        sb.append(", defInt1=").append(defInt1);
        sb.append(", defInt2=").append(defInt2);
        sb.append(", defInt3=").append(defInt3);
        sb.append(", defInt4=").append(defInt4);
        sb.append(", defInt5=").append(defInt5);
        sb.append(", defNum1=").append(defNum1);
        sb.append(", defNum2=").append(defNum2);
        sb.append(", defDt1=").append(defDt1);
        sb.append(", defDt2=").append(defDt2);
        sb.append("]");
        return sb.toString();
    }
}