package com.sun.entity.automodel;

import java.util.Date;

public class Fs_yhwd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.yhdm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String yhdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.wddm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String wddm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.yhmc
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String yhmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.wdmc
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String wdmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.addr
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.tel
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.cz
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String cz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.lxr
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String lxr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.yzbm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String yzbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.zh
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String zh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_str1
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String defStr1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_str2
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String defStr2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_str3
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String defStr3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_str4
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String defStr4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_str5
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String defStr5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_int1
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private int defInt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_int2
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private int defInt2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_int3
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private int defInt3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_int4
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private int defInt4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_int5
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private int defInt5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_num1
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String defNum1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_num2
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private String defNum2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_dt1
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private Date defDt1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fs_yhwd.def_dt2
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    private Date defDt2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.yhdm
     *
     * @return the value of fs_yhwd.yhdm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getYhdm() {
        return yhdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.yhdm
     *
     * @param yhdm the value for fs_yhwd.yhdm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setYhdm(String yhdm) {
        this.yhdm = yhdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.wddm
     *
     * @return the value of fs_yhwd.wddm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getWddm() {
        return wddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.wddm
     *
     * @param wddm the value for fs_yhwd.wddm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setWddm(String wddm) {
        this.wddm = wddm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.yhmc
     *
     * @return the value of fs_yhwd.yhmc
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getYhmc() {
        return yhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.yhmc
     *
     * @param yhmc the value for fs_yhwd.yhmc
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setYhmc(String yhmc) {
        this.yhmc = yhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.wdmc
     *
     * @return the value of fs_yhwd.wdmc
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getWdmc() {
        return wdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.wdmc
     *
     * @param wdmc the value for fs_yhwd.wdmc
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setWdmc(String wdmc) {
        this.wdmc = wdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.addr
     *
     * @return the value of fs_yhwd.addr
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.addr
     *
     * @param addr the value for fs_yhwd.addr
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.tel
     *
     * @return the value of fs_yhwd.tel
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.tel
     *
     * @param tel the value for fs_yhwd.tel
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.cz
     *
     * @return the value of fs_yhwd.cz
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getCz() {
        return cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.cz
     *
     * @param cz the value for fs_yhwd.cz
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setCz(String cz) {
        this.cz = cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.lxr
     *
     * @return the value of fs_yhwd.lxr
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getLxr() {
        return lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.lxr
     *
     * @param lxr the value for fs_yhwd.lxr
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setLxr(String lxr) {
        this.lxr = lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.yzbm
     *
     * @return the value of fs_yhwd.yzbm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getYzbm() {
        return yzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.yzbm
     *
     * @param yzbm the value for fs_yhwd.yzbm
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setYzbm(String yzbm) {
        this.yzbm = yzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.zh
     *
     * @return the value of fs_yhwd.zh
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getZh() {
        return zh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.zh
     *
     * @param zh the value for fs_yhwd.zh
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setZh(String zh) {
        this.zh = zh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_str1
     *
     * @return the value of fs_yhwd.def_str1
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getDefStr1() {
        return defStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_str1
     *
     * @param defStr1 the value for fs_yhwd.def_str1
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefStr1(String defStr1) {
        this.defStr1 = defStr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_str2
     *
     * @return the value of fs_yhwd.def_str2
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getDefStr2() {
        return defStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_str2
     *
     * @param defStr2 the value for fs_yhwd.def_str2
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefStr2(String defStr2) {
        this.defStr2 = defStr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_str3
     *
     * @return the value of fs_yhwd.def_str3
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getDefStr3() {
        return defStr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_str3
     *
     * @param defStr3 the value for fs_yhwd.def_str3
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefStr3(String defStr3) {
        this.defStr3 = defStr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_str4
     *
     * @return the value of fs_yhwd.def_str4
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getDefStr4() {
        return defStr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_str4
     *
     * @param defStr4 the value for fs_yhwd.def_str4
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefStr4(String defStr4) {
        this.defStr4 = defStr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_str5
     *
     * @return the value of fs_yhwd.def_str5
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getDefStr5() {
        return defStr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_str5
     *
     * @param defStr5 the value for fs_yhwd.def_str5
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefStr5(String defStr5) {
        this.defStr5 = defStr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_int1
     *
     * @return the value of fs_yhwd.def_int1
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public int getDefInt1() {
        return defInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_int1
     *
     * @param defInt1 the value for fs_yhwd.def_int1
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefInt1(int defInt1) {
        this.defInt1 = defInt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_int2
     *
     * @return the value of fs_yhwd.def_int2
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public int getDefInt2() {
        return defInt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_int2
     *
     * @param defInt2 the value for fs_yhwd.def_int2
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefInt2(int defInt2) {
        this.defInt2 = defInt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_int3
     *
     * @return the value of fs_yhwd.def_int3
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public int getDefInt3() {
        return defInt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_int3
     *
     * @param defInt3 the value for fs_yhwd.def_int3
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefInt3(int defInt3) {
        this.defInt3 = defInt3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_int4
     *
     * @return the value of fs_yhwd.def_int4
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public int getDefInt4() {
        return defInt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_int4
     *
     * @param defInt4 the value for fs_yhwd.def_int4
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefInt4(int defInt4) {
        this.defInt4 = defInt4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_int5
     *
     * @return the value of fs_yhwd.def_int5
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public int getDefInt5() {
        return defInt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_int5
     *
     * @param defInt5 the value for fs_yhwd.def_int5
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefInt5(int defInt5) {
        this.defInt5 = defInt5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_num1
     *
     * @return the value of fs_yhwd.def_num1
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getDefNum1() {
        return defNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_num1
     *
     * @param defNum1 the value for fs_yhwd.def_num1
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefNum1(String defNum1) {
        this.defNum1 = defNum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_num2
     *
     * @return the value of fs_yhwd.def_num2
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public String getDefNum2() {
        return defNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_num2
     *
     * @param defNum2 the value for fs_yhwd.def_num2
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefNum2(String defNum2) {
        this.defNum2 = defNum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_dt1
     *
     * @return the value of fs_yhwd.def_dt1
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public Date getDefDt1() {
        return defDt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_dt1
     *
     * @param defDt1 the value for fs_yhwd.def_dt1
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefDt1(Date defDt1) {
        this.defDt1 = defDt1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fs_yhwd.def_dt2
     *
     * @return the value of fs_yhwd.def_dt2
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public Date getDefDt2() {
        return defDt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fs_yhwd.def_dt2
     *
     * @param defDt2 the value for fs_yhwd.def_dt2
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    public void setDefDt2(Date defDt2) {
        this.defDt2 = defDt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fs_yhwd
     *
     * @mbg.generated Sun Jul 08 20:12:21 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", yhdm=").append(yhdm);
        sb.append(", wddm=").append(wddm);
        sb.append(", yhmc=").append(yhmc);
        sb.append(", wdmc=").append(wdmc);
        sb.append(", addr=").append(addr);
        sb.append(", tel=").append(tel);
        sb.append(", cz=").append(cz);
        sb.append(", lxr=").append(lxr);
        sb.append(", yzbm=").append(yzbm);
        sb.append(", zh=").append(zh);
        sb.append(", defStr1=").append(defStr1);
        sb.append(", defStr2=").append(defStr2);
        sb.append(", defStr3=").append(defStr3);
        sb.append(", defStr4=").append(defStr4);
        sb.append(", defStr5=").append(defStr5);
        sb.append(", defInt1=").append(defInt1);
        sb.append(", defInt2=").append(defInt2);
        sb.append(", defInt3=").append(defInt3);
        sb.append(", defInt4=").append(defInt4);
        sb.append(", defInt5=").append(defInt5);
        sb.append(", defNum1=").append(defNum1);
        sb.append(", defNum2=").append(defNum2);
        sb.append(", defDt1=").append(defDt1);
        sb.append(", defDt2=").append(defDt2);
        sb.append("]");
        return sb.toString();
    }
}